### ISSUE TITLE
License not applicable?

### ISSUE THREAD

**Issue by sateffen** [nodeca/argparse#161] opened 2021-03-24 14:21 UTC
Hey,

I've got a question about the chosen license: The [Python2.0 license](https://github.com/nodeca/argparse/blob/master/LICENSE)

The license-file grants explicit license between the Python Software Foundation / BeOpen.com / CNRI / CWI and the Licensee, about the software "Python", but not between nodeca and the Licensee about argparse. So, the license is basically not applicable and doesn't work. Is this intended?

[Python Software Foundation part](https://github.com/nodeca/argparse/blob/master/LICENSE#L62):

> 1. This LICENSE AGREEMENT is between the Python Software Foundation
("PSF"), and the Individual or Organization ("Licensee") accessing and
otherwise using this software ("Python") in source or binary form and
its associated documentation.

[BeOpen.com part](https://github.com/nodeca/argparse/blob/master/LICENSE#L112):

> 1. This LICENSE AGREEMENT is between BeOpen.com ("BeOpen"), having an
office at 160 Saratoga Avenue, Santa Clara, CA 95051, and the
Individual or Organization ("Licensee") accessing and otherwise using
this software in source or binary form and its associated
documentation ("the Software").

[CNRI part](https://github.com/nodeca/argparse/blob/master/LICENSE#L162):

> 1. This LICENSE AGREEMENT is between the Corporation for National
Research Initiatives, having an office at 1895 Preston White Drive,
Reston, VA 20191 ("CNRI"), and the Individual or Organization
("Licensee") accessing and otherwise using Python 1.6.1 software in
source or binary form and its associated documentation.

[CWI part](https://github.com/nodeca/argparse/blob/master/LICENSE#L233):

> Copyright (c) 1991 - 1995, Stichting Mathematisch Centrum Amsterdam,
The Netherlands.  All rights reserved.

I read [here](https://github.com/nodeca/argparse/issues/159#issuecomment-755444657) that you would chose a different license, but don't care about promoting yourself or want to apply any restrictions. The [MIT](https://choosealicense.com/licenses/mit/) license is quite popular with web-projects, but as far as I understand the right license for you might be the [UNLICENSE](https://choosealicense.com/licenses/unlicense/). It's basically "do whatever you want, no conditions, but if it's broken, I'm not at fault".

**Comment by puzrin** [comment] 2021-03-24 14:48
Seems dupe of #160. Please, continue there or in #159.

Also note, i'm not a lawyer, and talking with not lawyer will not add anything constructive (we can't operate with personal opinions). Probably, it would be better to ask python guys, what they think about licence for such port. If they confirm MIT as valid, i will change.

IMO using python license here is suitable, and does not add restrictions. Since this is port of python's v3.+ older parts of licence should be skipped (those exists because python version is universal, for all python's branches)

**Closed by puzrin** 2021-03-24 14:48 UTC

**Comment by puzrin** [comment] 2021-03-24 14:59
- `Python2.0 license` is version of licence, not version of python.
-  Applied parts depends on version of python.
- argparse is related to python 3.5.
